# Generated by Django 3.2.14 on 2022-07-15 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_bctalert_btcalert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='btcalert',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='btcalert',
            name='price_status',
            field=models.CharField(choices=[('created', 'created'), ('triggered', 'triggered'), ('deleted', 'deleted')], default='created', max_length=20),
        ),
    ]
